### ISSUE TITLE
Turn in to package

### ISSUE THREAD

**Issue by guysoft** [windmark/google-reminder-api-wrapper#1]
Great work!
Suggest this should be a package that can be added in to Pypi, it would require adding a ``setup.py`` file.

**Comment by windmark** [comment]
Yes indeed 👍I have it finished locally but will try it out and commit tomorrow.

**Comment by windmark** [comment]
Now it exists as a package in Pypi, https://pypi.org/project/google-reminder-api-wrapper/
@guysoft
